Algoritmo "EXERCICIO27"

// 27) Escreva um algoritmo que receba os três coeficientes de uma Equação do 2º Grau e calcule e
// exiba a(s) raiz(es) da equação, se existir(em). Se não existir, informar ao usuário. Caso o
// coeficiente “a” for igual à zero, informar que não se trata de uma equação do segundo grau e
// encerre o algoritmo.

Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo

// TESTE DE MESA